language: generic
cache:
  directories:
    - $HOME/.ccache/

matrix:
  include:
    - os: linux
      dist: xenial

addons:
  apt:
    update: true
    packages:
    # APT packages are organized into two groups, build dependency and 
    # development dependency, where the former is necessary for users who
    # want to build Zilliqa whereas the latter is only for CI.
    # Note that the names are sorted in each group.
    #
    # Build dependency
    - build-essential
    - cmake
    - libboost-system-dev
    - libboost-test-dev
    - libssl-dev
    - pkg-config
    # Development dependency
    - ccache
    - clang-5.0
    - clang-format-5.0
    - clang-tidy-5.0
    - curl
    - git
    - lcov
    - libxml2-utils
    - python-pip

script:
  - ./scripts/ci_build.sh

# Code coverage is currently only implemented for GCC builds, so OSX is currently excluded from reporting
after_success:
  - ./scripts/ci_report_coverage.sh
